<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $reportData['title'] }} - {{ config('app.name', 'AUTO AUDIT') }}</title>
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <!-- Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    
    <style>
        body { background-color: #f8f9fa; }
        .metric-card { transition: transform 0.2s; }
        .metric-card:hover { transform: translateY(-2px); }
        @media print {
            .no-print { display: none !important; }
            .page-break { page-break-before: always; }
        }
    </style>
</head>
<body>
    <!-- Page Header (matches main design) -->
    <div class="no-print mb-4">
        <div class="container">
            <div class="aa-card">
                <div class="card-header header-maroon d-flex justify-content-between align-items-center">
                    <h4 class="mb-0 text-white"><i class="bi bi-graph-up me-2"></i>{{ $reportData['title'] }}</h4>
                    <div class="d-flex align-items-center gap-2">
                        <a class="btn btn-warning btn-sm text-dark fw-semibold" href="{{ route('reports.index') }}">
                            <i class="bi bi-arrow-left me-1"></i>Back to Reports
                        </a>
                        <button onclick="window.print()" class="btn btn-warning btn-sm text-dark fw-semibold">
                            <i class="bi bi-printer me-1"></i>Print
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <!-- Report Info -->
        <div class="aa-card mb-4">
            <div class="card-header header-maroon">
                <h5 class="mb-0 text-white"><i class="bi bi-file-earmark-text me-2"></i>Report Details</h5>
            </div>
            <div class="card-body text-center">
                <h1 class="display-6 mb-2" style="color: var(--aa-maroon);">{{ $reportData['title'] }}</h1>
                <p class="lead mb-1">Period: {{ $reportData['period'] }}</p>
                <p class="mb-0">Generated by: {{ $reportData['generated_by'] }} on {{ $reportData['generated_on']->format('M d, Y \\a\\t h:i A') }}</p>
            </div>
        </div>

        <!-- Export Options -->
        <div class="card shadow-sm mb-4 no-print">
            <div class="card-header header-maroon">
                <h5 class="mb-0 text-white">
                    <i class="bi bi-download me-2"></i>Export Options
                </h5>
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <span></span>
                    <div class="btn-group">
                        <a href="{{ route('reports.export', 'excel') }}" class="btn btn-success">
                            <i class="bi bi-file-earmark-excel me-2"></i>Excel
                        </a>
                        <a href="{{ route('reports.export', 'pdf') }}" class="btn btn-danger">
                            <i class="bi bi-file-earmark-pdf me-2"></i>PDF
                        </a>
                        <a href="{{ route('reports.export', 'csv') }}" class="btn btn-info">
                            <i class="bi bi-file-earmark-text me-2"></i>CSV
                        </a>
                    </div>
                </div>
            </div>
        </div>

        @switch($reportData['type'])
            @case('attendance_summary')
                <!-- Attendance Summary Report -->
                <div class="row mb-4">
                    <div class="col-md-3">
                        <div class="card metric-card bg-primary text-white">
                            <div class="card-body text-center">
                                <h3 class="mb-0">{{ $reportData['summary']['total_records'] }}</h3>
                                <p class="mb-0">Total Records</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card metric-card bg-success text-white">
                            <div class="card-body text-center">
                                <h3 class="mb-0">{{ $reportData['summary']['unique_employees'] }}</h3>
                                <p class="mb-0">Unique Employees</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card metric-card bg-info text-white">
                            <div class="card-body text-center">
                                <h3 class="mb-0">{{ $reportData['summary']['average_hours_per_day'] }}</h3>
                                <p class="mb-0">Avg Hours/Day</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card metric-card bg-warning text-white">
                            <div class="card-body text-center">
                                <h3 class="mb-0">{{ $reportData['summary']['attendance_rate'] }}%</h3>
                                <p class="mb-0">Attendance Rate</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card shadow-sm mb-4">
                    <div class="card-header bg-light">
                        <h5 class="mb-0">
                            <i class="bi bi-list-ul me-2"></i>Detailed Statistics
                        </h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tbody>
                                    @foreach($reportData['summary'] as $key => $value)
                                        <tr>
                                            <th>{{ ucwords(str_replace('_', ' ', $key)) }}</th>
                                            <td>{{ $value }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                @break

            @case('employee_performance')
                <!-- Employee Performance Report -->
                <div class="card shadow-sm mb-4">
                    <div class="card-header bg-light">
                        <h5 class="mb-0">
                            <i class="bi bi-person-check me-2"></i>Employee Performance Summary
                        </h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead class="table-light">
                                    <tr>
                                        <th>Employee ID</th>
                                        <th>Employee Name</th>
                                        <th>Department</th>
                                        <th>Total Hours</th>
                                        <th>Overtime Hours</th>
                                        <th>Present Days</th>
                                        <th>Avg Hours/Day</th>
                                        <th>Attendance Rate</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($reportData['data'] as $employee)
                                        <tr>
                                            <td><code class="text-primary">#{{ $employee['employee_id'] }}</code></td>
                                            <td>{{ $employee['employee_name'] }}</td>
                                            <td><span class="badge bg-info">{{ $employee['department'] }}</span></td>
                                            <td class="fw-bold">{{ $employee['total_hours'] }}</td>
                                            <td class="text-warning">{{ $employee['overtime_hours'] }}</td>
                                            <td>{{ $employee['present_days'] }}</td>
                                            <td>{{ $employee['average_hours_per_day'] }}</td>
                                            <td>
                                                <span class="badge bg-{{ $employee['attendance_rate'] >= 90 ? 'success' : ($employee['attendance_rate'] >= 80 ? 'warning' : 'danger') }}">
                                                    {{ $employee['attendance_rate'] }}%
                                                </span>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                @break

            @case('department_comparison')
                <!-- Department Comparison Report -->
                <div class="card shadow-sm mb-4">
                    <div class="card-header bg-light">
                        <h5 class="mb-0">
                            <i class="bi bi-building me-2"></i>Department Performance Comparison
                        </h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead class="table-light">
                                    <tr>
                                        <th>Department</th>
                                        <th>Employee Count</th>
                                        <th>Total Hours</th>
                                        <th>Overtime Hours</th>
                                        <th>Avg Hours/Employee</th>
                                        <th>Attendance Rate</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($reportData['data'] as $dept)
                                        <tr>
                                            <td><strong>{{ $dept['department_name'] }}</strong></td>
                                            <td><span class="badge bg-secondary">{{ $dept['employee_count'] }}</span></td>
                                            <td class="fw-bold">{{ $dept['total_hours'] }}</td>
                                            <td class="text-warning">{{ $dept['overtime_hours'] }}</td>
                                            <td>{{ $dept['average_hours_per_employee'] }}</td>
                                            <td>
                                                <span class="badge bg-{{ $dept['attendance_rate'] >= 90 ? 'success' : ($dept['attendance_rate'] >= 80 ? 'warning' : 'danger') }}">
                                                    {{ $dept['attendance_rate'] }}%
                                                </span>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                @break

            @case('overtime_analysis')
                <!-- Overtime Analysis Report -->
                <div class="row mb-4">
                    <div class="col-md-3">
                        <div class="card metric-card bg-warning text-white">
                            <div class="card-body text-center">
                                <h3 class="mb-0">{{ $reportData['summary']['total_overtime_hours'] }}</h3>
                                <p class="mb-0">Total Overtime Hours</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card metric-card bg-info text-white">
                            <div class="card-body text-center">
                                <h3 class="mb-0">{{ $reportData['summary']['employees_with_overtime'] }}</h3>
                                <p class="mb-0">Employees with Overtime</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card metric-card bg-success text-white">
                            <div class="card-body text-center">
                                <h3 class="mb-0">{{ $reportData['summary']['average_overtime_per_employee'] }}</h3>
                                <p class="mb-0">Avg Overtime/Employee</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card metric-card bg-primary text-white">
                            <div class="card-body text-center">
                                <h3 class="mb-0">{{ $reportData['summary']['highest_overtime_employee']['employee_name'] ?? 'N/A' }}</h3>
                                <p class="mb-0">Highest Overtime Employee</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card shadow-sm mb-4">
                    <div class="card-header bg-light">
                        <h5 class="mb-0">
                            <i class="bi bi-clock-history me-2"></i>Employee Overtime Details
                        </h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead class="table-light">
                                    <tr>
                                        <th>Employee Name</th>
                                        <th>Total Overtime Hours</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($reportData['employee_overtime'] as $employee)
                                        <tr>
                                            <td>{{ $employee['employee_name'] }}</td>
                                            <td class="fw-bold text-warning">{{ $employee['total_overtime'] }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                @break

            @case('absenteeism_report')
                <!-- Absenteeism Report -->
                <div class="row mb-4">
                    <div class="col-md-3">
                        <div class="card metric-card bg-danger text-white">
                            <div class="card-body text-center">
                                <h3 class="mb-0">{{ $reportData['summary']['total_absences'] }}</h3>
                                <p class="mb-0">Total Absences</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card metric-card bg-warning text-white">
                            <div class="card-body text-center">
                                <h3 class="mb-0">{{ $reportData['summary']['employees_with_absences'] }}</h3>
                                <p class="mb-0">Employees with Absences</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card metric-card bg-info text-white">
                            <div class="card-body text-center">
                                <h3 class="mb-0">{{ $reportData['summary']['absence_rate'] }}%</h3>
                                <p class="mb-0">Absence Rate</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card metric-card bg-primary text-white">
                            <div class="card-body text-center">
                                <h3 class="mb-0">{{ $reportData['summary']['most_absent_employee']['employee_name'] ?? 'N/A' }}</h3>
                                <p class="mb-0">Most Absent Employee</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card shadow-sm mb-4">
                    <div class="card-header bg-light">
                        <h5 class="mb-0">
                            <i class="bi bi-person-x me-2"></i>Employee Absence Details
                        </h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead class="table-light">
                                    <tr>
                                        <th>Employee Name</th>
                                        <th>Department</th>
                                        <th>Absences</th>
                                        <th>Attendance Rate</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($reportData['employee_absences'] as $employee)
                                        <tr>
                                            <td>{{ $employee['employee_name'] }}</td>
                                            <td><span class="badge bg-info">{{ $employee['department'] }}</span></td>
                                            <td class="fw-bold text-danger">{{ $employee['absences'] }}</td>
                                            <td>
                                                <span class="badge bg-{{ $employee['attendance_rate'] >= 90 ? 'success' : ($employee['attendance_rate'] >= 80 ? 'warning' : 'danger') }}">
                                                    {{ $employee['attendance_rate'] }}%
                                                </span>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                @break
        @endswitch

        <!-- Report Footer -->
        <div class="card shadow-sm no-print">
            <div class="card-body text-center">
                <p class="text-muted mb-0">
                    <i class="bi bi-info-circle me-1"></i>
                    This report was generated on {{ $reportData['generated_on']->format('M d, Y \a\t h:i A') }} by {{ $reportData['generated_by'] }}
                </p>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
