<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $reportData['title'] }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #2c3e50;
            margin: 0;
        }
        .header p {
            margin: 5px 0;
            color: #7f8c8d;
        }
        .summary {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 30px;
        }
        .summary h3 {
            color: #2c3e50;
            margin-top: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .metric {
            display: inline-block;
            margin: 10px;
            padding: 15px;
            background: #3498db;
            color: white;
            border-radius: 5px;
            text-align: center;
            min-width: 120px;
        }
        .metric h4 {
            margin: 0;
            font-size: 24px;
        }
        .metric p {
            margin: 5px 0 0 0;
            font-size: 12px;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            color: #7f8c8d;
            font-size: 12px;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $reportData['title'] }}</h1>
        <p><strong>Period:</strong> {{ $reportData['period'] }}</p>
        <p><strong>Generated by:</strong> {{ $reportData['generated_by'] }}</p>
        <p><strong>Generated on:</strong> {{ $reportData['generated_on']->format('M d, Y \a\t h:i A') }}</p>
    </div>

    @switch($reportData['type'])
        @case('attendance_summary')
            <div class="summary">
                <h3>Summary Statistics</h3>
                <div class="metric">
                    <h4>{{ $reportData['summary']['total_records'] }}</h4>
                    <p>Total Records</p>
                </div>
                <div class="metric">
                    <h4>{{ $reportData['summary']['unique_employees'] }}</h4>
                    <p>Unique Employees</p>
                </div>
                <div class="metric">
                    <h4>{{ $reportData['summary']['average_hours_per_day'] }}</h4>
                    <p>Avg Hours/Day</p>
                </div>
                <div class="metric">
                    <h4>{{ $reportData['summary']['attendance_rate'] }}%</h4>
                    <p>Attendance Rate</p>
                </div>
            </div>
            @break

        @case('employee_performance')
            <h3>Employee Performance Summary</h3>
            <table>
                <thead>
                    <tr>
                        <th>Employee ID</th>
                        <th>Employee Name</th>
                        <th>Department</th>
                        <th>Total Hours</th>
                        <th>Overtime Hours</th>
                        <th>Present Days</th>
                        <th>Avg Hours/Day</th>
                        <th>Attendance Rate</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reportData['data'] as $employee)
                        <tr>
                            <td>{{ $employee['employee_id'] }}</td>
                            <td>{{ $employee['employee_name'] }}</td>
                            <td>{{ $employee['department'] }}</td>
                            <td>{{ $employee['total_hours'] }}</td>
                            <td>{{ $employee['overtime_hours'] }}</td>
                            <td>{{ $employee['present_days'] }}</td>
                            <td>{{ $employee['average_hours_per_day'] }}</td>
                            <td>{{ $employee['attendance_rate'] }}%</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            @break

        @case('department_comparison')
            <h3>Department Performance Comparison</h3>
            <table>
                <thead>
                    <tr>
                        <th>Department</th>
                        <th>Employee Count</th>
                        <th>Total Hours</th>
                        <th>Overtime Hours</th>
                        <th>Avg Hours/Employee</th>
                        <th>Attendance Rate</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reportData['data'] as $dept)
                        <tr>
                            <td>{{ $dept['department_name'] }}</td>
                            <td>{{ $dept['employee_count'] }}</td>
                            <td>{{ $dept['total_hours'] }}</td>
                            <td>{{ $dept['overtime_hours'] }}</td>
                            <td>{{ $dept['average_hours_per_employee'] }}</td>
                            <td>{{ $dept['attendance_rate'] }}%</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            @break

        @case('overtime_analysis')
            <div class="summary">
                <h3>Overtime Analysis Summary</h3>
                <div class="metric">
                    <h4>{{ $reportData['summary']['total_overtime_hours'] }}</h4>
                    <p>Total Overtime Hours</p>
                </div>
                <div class="metric">
                    <h4>{{ $reportData['summary']['employees_with_overtime'] }}</h4>
                    <p>Employees with Overtime</p>
                </div>
                <div class="metric">
                    <h4>{{ $reportData['summary']['average_overtime_per_employee'] }}</h4>
                    <p>Avg Overtime/Employee</p>
                </div>
            </div>

            <h3>Employee Overtime Details</h3>
            <table>
                <thead>
                    <tr>
                        <th>Employee Name</th>
                        <th>Total Overtime Hours</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reportData['employee_overtime'] as $employee)
                        <tr>
                            <td>{{ $employee['employee_name'] }}</td>
                            <td>{{ $employee['total_overtime'] }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            @break

        @case('absenteeism_report')
            <div class="summary">
                <h3>Absenteeism Summary</h3>
                <div class="metric">
                    <h4>{{ $reportData['summary']['total_absences'] }}</h4>
                    <p>Total Absences</p>
                </div>
                <div class="metric">
                    <h4>{{ $reportData['summary']['employees_with_absences'] }}</h4>
                    <p>Employees with Absences</p>
                </div>
                <div class="metric">
                    <h4>{{ $reportData['summary']['absence_rate'] }}%</h4>
                    <p>Absence Rate</p>
                </div>
            </div>

            <h3>Employee Absence Details</h3>
            <table>
                <thead>
                    <tr>
                        <th>Employee Name</th>
                        <th>Department</th>
                        <th>Absences</th>
                        <th>Attendance Rate</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reportData['employee_absences'] as $employee)
                        <tr>
                            <td>{{ $employee['employee_name'] }}</td>
                            <td>{{ $employee['department'] }}</td>
                            <td>{{ $employee['absences'] }}</td>
                            <td>{{ $employee['attendance_rate'] }}%</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            @break
    @endswitch

    <div class="footer">
        <p>This report was generated on {{ $reportData['generated_on']->format('M d, Y \a\t h:i A') }} by {{ $reportData['generated_by'] }}</p>
        <p>© {{ date('Y') }} {{ config('app.name', 'Laravel') }} - All rights reserved</p>
    </div>
</body>
</html>
