@extends('layouts.theme')
@section('content')
    <div class="container-fluid">
        <!-- Success/Error Messages REMOVED (handled by toasts)-->
        {{-- Alerts removed --}}
        <!-- Report Header -->
        <div class="aa-card mb-4">
            <div class="card-header header-maroon d-flex justify-content-between align-items-center">
                <h3 class="fw-bold mb-0 text-white">
                    <i class="bi bi-file-earmark-text me-2 fs-4"></i>{{ $report->report_title }}
                </h3>
                <div class="dropdown">
                    <button class="btn btn-warning dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-download me-2"></i>Download
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="{{ route('dtr.download', [$report->report_id, 'html']) }}"><i class="bi bi-filetype-html me-2 text-primary"></i>HTML</a></li>
                        <li><a class="dropdown-item" href="{{ route('dtr.download', [$report->report_id, 'pdf']) }}"><i class="bi bi-filetype-pdf me-2 text-danger"></i>PDF</a></li>
                        <li><a class="dropdown-item" href="{{ route('dtr.download', [$report->report_id, 'csv']) }}"><i class="bi bi-filetype-csv me-2 text-success"></i>CSV</a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body">
                <div class="row text-center">
                    <div class="col-md-3">
                        <div class="rounded p-3">
                            <h3 class="text-primary"><i class="bi bi-building me-2"></i>{{ $report->department_name }}</h3>
                            <p class="mb-0">Office</p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="rounded p-3">
                            <h3 class="text-success"><i class="bi bi-calendar-check me-2"></i>{{ ucfirst($report->report_type) }}</h3>
                            <p class="mb-0">Report Type</p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="rounded p-3">
                            <h3 class="text-info"><i class="bi bi-calendar-range me-2"></i>{{ $report->formatted_period }}</h3>
                            <p class="mb-0">Period</p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="rounded p-3">
                            <h3 class="text-warning"><i class="bi bi-people me-2"></i>{{ $report->total_employees }}</h3>
                            <p class="mb-0">Total Employees</p>
                        </div>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-6">
                        <p><i class="bi bi-person-badge me-2"></i><strong>Generated By:</strong> {{ $report->admin_name }}</p>
                    </div>
                    <div class="col-md-6">
                        <p><i class="bi bi-clock me-2"></i><strong>Generated On:</strong> {{ $report->formatted_generated_on }}</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Employee Summaries -->
        <div class="aa-card mb-4">
            <div class="card-header header-maroon">
                <h5 class="mb-0 text-white">
                    <i class="bi bi-people me-2"></i>Employee Summaries
                </h5>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th><i class="bi bi-person"></i>Employee</th>
                                <th><i class="bi bi-calendar-check"></i>Total Days</th>
                                <th><i class="bi bi-check-circle"></i>Present Days</th>
                                <th><i class="bi bi-x-circle"></i>Absent Days</th>
                                <th><i class="bi bi-exclamation-triangle"></i>Incomplete Days</th>
                                <th><i class="bi bi-clock"></i>Total Hours</th>
                                <th><i class="bi bi-stopwatch"></i>Overtime Hours</th>
                                <th><i class="bi bi-graph-up"></i>Avg Hours/Day</th>
                                <th><i class="bi bi-percent"></i>Attendance Rate</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($report->summaries as $summary)
                                <tr>
                                    <td>
                                        <div class="fw-bold">{{ $summary->employee->full_name }}</div>
                                        <small class="text-muted">ID: {{ $summary->employee->employee_id }}</small>
                                    </td>
                                    <td>{{ $summary->total_days }}</td>
                                    <td>
                                        <span class="badge bg-success">{{ $summary->present_days }}</span>
                                    </td>
                                    <td>
                                        <span class="badge bg-danger">{{ $summary->absent_days }}</span>
                                    </td>
                                    <td>
                                        <span class="badge bg-info">{{ $summary->incomplete_days }}</span>
                                    </td>
                                    <td class="fw-bold text-success">{{ $summary->total_hours_formatted }}</td>
                                    <td class="text-warning">{{ $summary->overtime_hours_formatted }}</td>
                                    <td>{{ $summary->average_hours_formatted }}</td>
                                    <td>
                                        <span class="badge {{ $summary->attendance_status_class }}">
                                            {{ $summary->attendance_rate_percentage }}
                                        </span>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <!-- Detailed Attendance Records -->
        @foreach($report->summaries as $summary)
            <div class="aa-card mb-4">
                <div class="card-header header-maroon">
                    <h5 class="mb-0">
                        <i class="bi bi-person me-2"></i>{{ $summary->employee->full_name }} - Detailed Attendance
                    </h5>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-sm">
                            <thead>
                                <tr>
                                    <th><i class="bi bi-calendar-date"></i>Date</th>
                                    <th><i class="bi bi-calendar-week"></i>Day</th>
                                    <th><i class="bi bi-arrow-right-circle"></i>Time In</th>
                                    <th><i class="bi bi-arrow-left-circle"></i>Time Out</th>
                                    <th><i class="bi bi-clock"></i>Total Hours</th>
                                    <th><i class="bi bi-stopwatch"></i>Overtime</th>
                                    <th><i class="bi bi-flag"></i>Status</th>
                                    <th><i class="bi bi-chat-text"></i>Remarks</th>
                                    <th class="no-print"><i class="bi bi-gear"></i>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($report->details->where('employee_id', $summary->employee_id) as $detail)
                                    <tr>
                                        <td>{{ $detail->formatted_date }}</td>
                                        <td>{{ \Carbon\Carbon::parse($detail->date)->format('D') }}</td>
                                        <td>{{ $detail->formatted_time_in }}</td>
                                        <td>{{ $detail->formatted_time_out }}</td>
                                        <td class="fw-bold">{{ number_format($detail->total_hours, 2) }}</td>
                                        <td class="text-warning">{{ number_format($detail->overtime_hours, 2) }}</td>
                                        @php
                                            $dateKey = \Carbon\Carbon::parse($detail->date)->toDateString();
                                            $ovKey = $summary->employee->employee_id.'|'.$dateKey;
                                            $ov = isset($overrides) ? ($overrides[$ovKey] ?? null) : null;
                                        @endphp
                                        <td>
                                            @if($ov)
                                                <span class="badge bg-secondary">Leave</span>
                                            @else
                                                <span class="badge {{ $detail->status_badge_class }}">{{ ucfirst($detail->status) }}</span>
                                            @endif
                                        </td>
                                        <td>
                                            <small class="text-muted">@if($ov) {{ 'Leave'.($ov->remarks?': '.$ov->remarks:'') }} @else {{ $detail->remarks }} @endif</small>
                                        </td>
                                        <td class="no-print">
                                            <div class="btn-group btn-group-sm">
                                                @if($ov)
                                                    <button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#ovModal_{{ $summary->employee->employee_id }}_{{ \Carbon\Carbon::parse($detail->date)->toDateString() }}">
                                                        <i class="bi bi-pencil"></i>
                                                    </button>
                                                    <button class="btn btn-outline-danger remove-override-btn" data-report-id="{{ $report->report_id }}" data-employee-id="{{ $summary->employee->employee_id }}" data-date="{{ \Carbon\Carbon::parse($detail->date)->toDateString() }}">
                                                        <i class="bi bi-x-circle"></i>
                                                    </button>
                                                @else
                                                    <button class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#ovModal_{{ $summary->employee->employee_id }}_{{ \Carbon\Carbon::parse($detail->date)->toDateString() }}">
                                                        <i class="bi bi-clipboard-plus"></i>
                                                    </button>
                                                @endif
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            @foreach($report->details->where('employee_id', $summary->employee_id) as $detail)
            @php 
                $dateKey = \Carbon\Carbon::parse($detail->date)->toDateString();
                $ovKey = $summary->employee->employee_id.'|'.$dateKey; 
                $ov = isset($overrides) ? ($overrides[$ovKey] ?? null) : null;
            @endphp
            <div class="modal fade" id="ovModal_{{ $summary->employee->employee_id }}_{{ $dateKey }}" tabindex="-1">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content border-0 shadow-lg" style="border-radius: 12px; overflow: hidden;">
                        <div class="modal-header header-maroon d-flex justify-content-between align-items-center">
                            <h5 class="modal-title text-white mb-0">@if($ov) Edit Leave @else Mark as Leave @endif - {{ $summary->employee->full_name }} ({{ \Carbon\Carbon::parse($detail->date)->format('M d, Y') }})</h5>
                            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
                        </div>
                        <form action="{{ route('dtr.override.store') }}" method="POST">
                            @csrf
                            <div class="modal-body p-4" style="background: #fafbfc;">
                                <input type="hidden" name="report_id" value="{{ $report->report_id }}">
                                <input type="hidden" name="employee_id" value="{{ $summary->employee->employee_id }}">
                                <input type="hidden" name="date" value="{{ $dateKey }}">
                                <div class="mb-3">
                                    <label class="form-label fw-semibold" style="color: var(--aa-maroon);">Remarks (optional)</label>
                                    <input type="text" name="remarks" class="form-control form-control-lg border-2" placeholder="Reason or notes" value="{{ $ov? $ov->remarks : '' }}" style="border-color: #e5e7eb; border-radius: 8px; padding: 12px 16px;">
                                </div>
                                <div class="form-text">This overlay does not change stored attendance, only how this DTR shows/exports.</div>
                            </div>
                            <div class="modal-footer border-0 p-4" style="background: white;">
                                <button type="button" class="btn btn-lg px-4 me-2" data-bs-dismiss="modal" style="background: #f8f9fa; color: #6c757d; border: 2px solid #e5e7eb; border-radius: 8px; font-weight: 600;">Cancel</button>
                                <button type="submit" class="btn btn-lg px-4 fw-bold text-white" style="background: linear-gradient(135deg, var(--aa-maroon), var(--aa-maroon-dark)); border: none; border-radius: 8px;">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            @endforeach
        @endforeach

        <!-- Report Summary -->
        <div class="aa-card mb-4">
            <div class="card-header header-maroon">
                <h5 class="mb-0 text-white">
                    <i class="bi bi-graph-up me-2"></i>Report Summary
                </h5>
            </div>
            <div class="card-body">
                <div class="row text-center">
                    <div class="col-md-3">
                        <div class="rounded p-3">
                            <h3 class="text-primary">{{ $report->total_employees }}</h3>
                            <p class="mb-0">Total Employees</p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="rounded p-3">
                            <h3 class="text-success">{{ $report->total_days }}</h3>
                            <p class="mb-0">Total Days</p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="rounded p-3">
                            <h3 class="text-info">{{ number_format($report->total_hours, 2) }}</h3>
                            <p class="mb-0">Total Hours</p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="rounded p-3">
                            <h3 class="text-warning">{{ $report->summaries->avg('attendance_rate') ? number_format($report->summaries->avg('attendance_rate'), 1) : '0' }}%</h3>
                            <p class="mb-0">Avg Attendance Rate</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('layouts.toast-js')
    <script>
        document.addEventListener('click', function (event) {
            const target = event.target.closest('.remove-override-btn');
            if (!target) return;

            const reportId = target.getAttribute('data-report-id');
            const employeeId = target.getAttribute('data-employee-id');
            const dateStr = target.getAttribute('data-date');

            if (!confirm('Remove leave for ' + dateStr + '?')) return;

            const form = document.createElement('form');
            form.method = 'POST';
            form.action = "{{ route('dtr.override.destroy') }}";

            const csrf = document.createElement('input');
            csrf.type = 'hidden';
            csrf.name = '_token';
            csrf.value = '{{ csrf_token() }}';
            form.appendChild(csrf);

            const method = document.createElement('input');
            method.type = 'hidden';
            method.name = '_method';
            method.value = 'DELETE';
            form.appendChild(method);

            const rid = document.createElement('input');
            rid.type = 'hidden';
            rid.name = 'report_id';
            rid.value = reportId;
            form.appendChild(rid);

            const emp = document.createElement('input');
            emp.type = 'hidden';
            emp.name = 'employee_id';
            emp.value = employeeId;
            form.appendChild(emp);

            const date = document.createElement('input');
            date.type = 'hidden';
            date.name = 'date';
            date.value = dateStr;
            form.appendChild(date);

            document.body.appendChild(form);
            form.submit();
        });
    </script>
@endsection
